import { deepStrictEqual, strictEqual } from 'node:assert';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, afterEach, before, beforeEach, describe, it } from 'node:test';

import { BANNER } from '../../../src/ohne/codegen/codegen-dir.ts';
import {
  bootProject,
  loadLayers,
  queryMetadata,
  useCollections,
  useEnv,
  useLayers,
  usePrinter,
  useRoutes,
  version,
} from '../../../src/ohne/index.ts';
import { relativePath } from '../../../src/utils/index.ts';

const FRAMEWORK = join(import.meta.dirname, '..', '..', '..');

const REGISTRATIONS = ['routes', 'middleware', 'messages', 'database', 'roles', 'skills'];

const scope = globalThis as typeof globalThis & { __ohneBootProject: unknown[] };

describe('bootProject', () => {
  let root: string;

  function write(file: string, content: string): void {
    mkdirSync(join(file, '..'), { recursive: true });
    writeFileSync(file, content);
  }

  function mark(file: string, label: string): void {
    write(file, `globalThis.__ohneBootProject.push(${JSON.stringify(label)});\n`);
  }

  function makeApp(name: string, layers: string[] = []): string {
    const app = join(root, name);
    const dependencies = Object.fromEntries(layers.map((layer) => [layer, '*']));
    write(join(app, 'package.json'), JSON.stringify({ name, type: 'module', dependencies }));
    write(join(app, 'ohne.config.ts'), `export default ${JSON.stringify({ layers })};\n`);
    return app;
  }

  function link(app: string, name: string, target: string): void {
    mkdirSync(join(app, 'node_modules'), { recursive: true });
    symlinkSync(target, join(app, 'node_modules', name), 'dir');
  }

  async function bootCapturing(app: string): Promise<string> {
    const out: string[] = [];
    usePrinter().configure({ stream: { write: (chunk) => out.push(chunk) } });
    try {
      await bootProject(app);
    } finally {
      usePrinter().configure({ stream: process.stderr });
    }
    return out.join('');
  }

  async function bootSkipping(app: string): Promise<string> {
    useEnv().set('SKIP_CODEGEN', true);
    await loadLayers(app);
    return bootCapturing(app);
  }

  before(() => {
    root = realpathSync(mkdtempSync(join(tmpdir(), 'ohne-boot-project-')));
    useEnv().set('NO_COLOR', true);
  });

  after(() => {
    useEnv().unset('NO_COLOR');
    rmSync(root, { recursive: true, force: true });
  });

  beforeEach(() => {
    scope.__ohneBootProject = [];
  });

  afterEach(() => {
    useEnv().unset('SKIP_CODEGEN');
    useLayers().clear();
    useRoutes().clear();
    useCollections().clear();
  });

  it('runs the boot files of every layer, furthest-first', async () => {
    const base = makeApp('base');
    mark(join(base, 'boot', 'index.ts'), 'base');
    const app = makeApp('layered', ['base']);
    link(app, 'base', base);
    mark(join(app, 'boot', 'index.ts'), 'app');
    await loadLayers(app);

    await bootProject(app);

    deepStrictEqual(scope.__ohneBootProject, ['base', 'app']);
  });

  it('boots, then regenerates the codegen files', async () => {
    const app = makeApp('regen');
    const routes = join(app, '.ohne', 'node', 'routes.ts');
    const stale = '// Generated by ohne 0.0.0. Do not edit.';
    write(routes, `${stale}\nexport {};\n`);
    write(
      join(app, 'boot', 'index.ts'),
      "import { readFileSync } from 'node:fs';\n" +
        `const [head] = readFileSync(${JSON.stringify(routes)}, 'utf8').split('\\n');\n` +
        'globalThis.__ohneBootProject.push(head);\n',
    );
    await loadLayers(app);

    await bootProject(app);

    deepStrictEqual(scope.__ohneBootProject, [stale]);
    strictEqual(readFileSync(routes, 'utf8').split('\n')[0], BANNER);
    strictEqual(existsSync(join(app, '.ohne', 'node', 'layer-name.ts')), true);
  });

  it('leaves the codegen dir untouched under `SKIP_CODEGEN`', async () => {
    const app = makeApp('skip');
    mark(join(app, 'boot', 'index.ts'), 'skip');
    const routes = join(app, '.ohne', 'node', 'routes.ts');
    const dropped = join(app, '.ohne', 'node', 'dropped.ts');
    write(routes, `${BANNER}\nexport {};\n`);
    write(dropped, `${BANNER}\n`);

    await bootSkipping(app);

    deepStrictEqual(scope.__ohneBootProject, ['skip']);
    strictEqual(readFileSync(routes, 'utf8'), `${BANNER}\nexport {};\n`);
    strictEqual(existsSync(dropped), true);
    strictEqual(existsSync(join(app, '.ohne', 'node', 'layer-name.ts')), false);
  });

  it('imports each generated registration file in turn, and no other', async () => {
    const app = makeApp('imports');
    for (const name of [...REGISTRATIONS, 'layer-name', 'resolved-config']) {
      write(
        join(app, '.ohne', 'node', `${name}.ts`),
        `${BANNER}\nglobalThis.__ohneBootProject.push(${JSON.stringify(name)});\n`,
      );
    }
    write(
      join(app, '.ohne', 'shared', 'routes.ts'),
      `${BANNER}\nglobalThis.__ohneBootProject.push('shared');\n`,
    );

    await bootSkipping(app);

    deepStrictEqual(scope.__ohneBootProject, REGISTRATIONS);
  });

  it('registers the generated routes and collections', async () => {
    const app = makeApp('registered');
    link(app, 'ohnejs', FRAMEWORK);
    write(
      join(app, 'api', 'ping.get.ts'),
      "import { defineHandler } from 'ohnejs';\nexport default defineHandler(() => 'pong');\n",
    );
    write(
      join(app, 'collections', 'Heroes.ts'),
      "import { defineCollection, field } from 'ohnejs';\n" +
        "export default defineCollection({ fields: { name: field('text') } });\n",
    );
    await loadLayers(app);

    await bootProject(app);

    strictEqual(useRoutes().has('GET /ping'), true);
    deepStrictEqual(Object.keys(queryMetadata('Heroes').fields), ['UUID', '_updatedAt', 'name']);
  });

  it('warns under `SKIP_CODEGEN` when another ohne version generated the files', async () => {
    const app = makeApp('foreign');
    write(
      join(app, '.ohne', 'node', 'routes.ts'),
      '// Generated by ohne 0.0.0. Do not edit.\nexport {};\n',
    );

    const text = await bootSkipping(app);

    strictEqual(text.includes('Generated files are stale'), true);
    strictEqual(text.includes(`generated by ohne 0.0.0; you are running ${version}.`), true);
    strictEqual(text.includes(relativePath(process.cwd(), join(app, '.ohne'))), true);
  });

  it('warns under `SKIP_CODEGEN` when the files carry no version stamp', async () => {
    const app = makeApp('unstamped');
    write(
      join(app, '.ohne', 'node', 'routes.ts'),
      '// Generated by ohne. Do not edit.\nexport {};\n',
    );

    const text = await bootSkipping(app);

    strictEqual(text.includes('Generated files are stale'), true);
    strictEqual(text.includes(`so an earlier ohne than ${version} generated them.`), true);
  });

  it('reads the stamp from the first registration file present', async () => {
    const app = makeApp('partial');
    write(
      join(app, '.ohne', 'node', 'messages.ts'),
      '// Generated by ohne 0.0.0. Do not edit.\nexport {};\n',
    );
    write(join(app, '.ohne', 'node', 'roles.ts'), `${BANNER}\nexport {};\n`);

    const text = await bootSkipping(app);

    strictEqual(text.includes('generated by ohne 0.0.0'), true);
  });

  it('stays quiet under `SKIP_CODEGEN` when the stamp matches the running version', async () => {
    const app = makeApp('fresh');
    write(join(app, '.ohne', 'node', 'routes.ts'), `${BANNER}\nexport {};\n`);

    strictEqual(await bootSkipping(app), '');
  });

  it('boots quietly under `SKIP_CODEGEN` when the codegen dir is missing', async () => {
    const app = makeApp('bare');
    mark(join(app, 'boot', 'index.ts'), 'bare');

    strictEqual(await bootSkipping(app), '');
    deepStrictEqual(scope.__ohneBootProject, ['bare']);
    strictEqual(existsSync(join(app, '.ohne')), false);
  });

  it('boots and writes nothing when no package.json is found', async () => {
    const loose = join(root, 'loose');
    mark(join(loose, 'boot', 'index.ts'), 'loose');
    useLayers().add({ path: loose, input: {} });

    await bootProject(loose);

    deepStrictEqual(scope.__ohneBootProject, ['loose']);
    strictEqual(existsSync(join(loose, '.ohne')), false);
  });
});
