import { strictEqual } from 'node:assert';
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, before, describe, it } from 'node:test';

import { ohne } from '../../../../src/ohne/cli/ohne.ts';
import { useEnv } from '../../../../src/ohne/index.ts';
import { runCommand } from '../../../../src/utils/cli/index.ts';

describe('ohne prepare', () => {
  let root: string;

  function makeDir(name: string, ohneProject: boolean): string {
    const dir = mkdtempSync(join(root, `${name}-`));
    writeFileSync(join(dir, 'package.json'), JSON.stringify({ name }));
    if (ohneProject) writeFileSync(join(dir, 'ohne.config.ts'), '');
    return dir;
  }

  before(() => {
    root = mkdtempSync(join(tmpdir(), 'ohne-prepare-'));
    useEnv().set('SILENT', true);
    process.exitCode = 0;
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
    useEnv().unset('SILENT');
    process.exitCode = 0;
  });

  it('generates the codegen files for an ohne project', async () => {
    const dir = makeDir('app', true);

    const code = await runCommand(ohne, ['prepare', '--cwd', dir]);
    strictEqual(code, 0);
    strictEqual(process.exitCode, 0);
    strictEqual(existsSync(join(dir, '.ohne', 'node', 'layer-name.ts')), true);
    strictEqual(existsSync(join(dir, '.ohne', 'node', 'resolved-config.ts')), true);
  });

  it('prunes files an earlier run left in the codegen dir', async () => {
    const dir = makeDir('stale', true);
    mkdirSync(join(dir, '.ohne', 'node'), { recursive: true });
    writeFileSync(join(dir, '.ohne', 'flat.ts'), '// Generated by ohne. Do not edit.\n');
    writeFileSync(join(dir, '.ohne', 'node', 'stale.ts'), '// Generated by ohne. Do not edit.\n');

    const code = await runCommand(ohne, ['prepare', '--cwd', dir]);
    strictEqual(code, 0);
    strictEqual(existsSync(join(dir, '.ohne', 'flat.ts')), false);
    strictEqual(existsSync(join(dir, '.ohne', 'node', 'stale.ts')), false);
    strictEqual(existsSync(join(dir, '.ohne', 'node', 'layer-name.ts')), true);
  });

  it('refuses to run outside an ohne project', async () => {
    const dir = makeDir('plain', false);

    await runCommand(ohne, ['prepare', '--cwd', dir]);
    strictEqual(process.exitCode, 1);
    strictEqual(existsSync(join(dir, '.ohne')), false);
  });
});
