import { listDir } from '../fs/list-dir.ts';
import { removeFile } from '../fs/remove-file.ts';
import { writeFileIfChanged } from '../fs/write-file-if-changed.ts';
import { isNull } from '../is/is-null.ts';
import { isUndefined } from '../is/is-undefined.ts';
import { isAbsolutePath } from '../path/is-absolute-path.ts';
import { joinPath } from '../path/join-path.ts';
import { normalizePath } from '../path/normalize-path.ts';
import { relativePath as toRelative } from '../path/relative-path.ts';

/**
 * Options for `createGenerator`.
 */
export interface GeneratorOptions {
  /**
   * Output directory every path is resolved against.
   * Resolved against `process.cwd()` when relative.
   */
  dir: string;

  /**
   * Text prepended to every written file, followed by a newline.
   * Use it to mark output as generated, e.g. `'// Generated by ohne. Do not edit.'`.
   *
   * @default
   * undefined
   */
  banner?: string;
}

/**
 * A directory-scoped code generator returned by `createGenerator`.
 *
 * `write` only touches files that actually changed and remembers every path it produced.
 * `prune` then deletes whatever it did not produce, leaving only the current output.
 */
export interface Generator {
  /**
   * The resolved, absolute output directory.
   */
  readonly dir: string;

  /**
   * Resolves `relativePath` against the output directory and returns the absolute path.
   */
  path(relativePath: string): string;

  /**
   * Writes `content` to `relativePath`, prepending the banner if one is set.
   * Skips the write when the file is already up to date.
   * Records the path so a later `prune` keeps it.
   * Returns `true` if a write happened, `false` if it was unchanged.
   */
  write(relativePath: string, content: string): Promise<boolean>;

  /**
   * Returns the relative path of every file written so far, in write order.
   */
  written(): string[];

  /**
   * Deletes every file under the output directory that was not written this run.
   * Leaves directories in place.
   * Returns the relative paths that were removed.
   */
  prune(): Promise<string[]>;
}

/**
 * Creates a directory-scoped generator for robust, repeatable code generation.
 *
 * Each run writes the full set of files, then `prune` removes anything left from a previous run.
 * Output stays deterministic, and unchanged files are never rewritten so watchers stay quiet.
 *
 * @example
 * ```ts
 * const gen = createGenerator({ dir: '.ohne', banner: '// Generated by ohne. Do not edit.' })
 *
 * await gen.write('imports.ts', imports) // -> true on first run, false when unchanged
 * await gen.write('types.d.ts', types)
 *
 * await gen.prune() // -> ['stale.ts'] removes files this run did not write
 * ```
 */
export function createGenerator(options: GeneratorOptions): Generator {
  const { dir, banner } = options;
  const root = isAbsolutePath(dir) ? normalizePath(dir) : joinPath(process.cwd(), dir);
  const written = new Set<string>();

  const generator: Generator = {
    dir: root,

    path(relativePath) {
      return joinPath(root, relativePath);
    },

    write(relativePath, content) {
      const target = joinPath(root, relativePath);
      written.add(toRelative(root, target));
      const body = isUndefined(banner) ? content : `${banner}\n${content}`;
      return writeFileIfChanged(target, body);
    },

    written() {
      return [...written];
    },

    async prune() {
      const entries = await listDir(root, { files: true, dirs: false });
      if (isNull(entries)) return [];
      const removed: string[] = [];
      for (const entry of entries) {
        if (!written.has(entry.relativePath)) {
          await removeFile(entry.path);
          removed.push(entry.relativePath);
        }
      }
      return removed;
    },
  };

  return generator;
}
