import { strictEqual } from 'node:assert';
import { describe, it } from 'node:test';

import { BANNER, BANNER_PREFIX, bannerVersion } from '../../../src/ohne/codegen/codegen-dir.ts';
import { version } from '../../../src/ohne/meta/version.ts';

describe('bannerVersion', () => {
  it('reads the stamped version from generated content', () => {
    strictEqual(bannerVersion(`${BANNER}\nexport {};\n`), version);
  });

  it('returns null for the unversioned banner of early ohne', () => {
    strictEqual(bannerVersion('// Generated by ohne. Do not edit.\n'), null);
  });

  it('returns null for content without a banner', () => {
    strictEqual(bannerVersion('export const mine = true;\n'), null);
  });

  it('the banner starts with the version-independent prefix', () => {
    strictEqual(BANNER.startsWith(BANNER_PREFIX), true);
  });
});
