import { deepStrictEqual, strictEqual } from 'node:assert';
import { existsSync, mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, afterEach, before, describe, it } from 'node:test';

import { BANNER } from '../../../src/ohne/codegen/codegen-dir.ts';
import { generateProject, loadLayers, useLayers } from '../../../src/ohne/index.ts';

const ohne = new URL('../../../src/ohne/index.ts', import.meta.url).href;

describe('generateProject', () => {
  let root: string;

  function makeApp(name: string): string {
    const app = join(root, name);
    mkdirSync(app, { recursive: true });
    writeFileSync(join(app, 'package.json'), JSON.stringify({ name, type: 'module' }));
    writeFileSync(join(app, 'ohne.config.ts'), '');
    writeFileSync(
      join(app, 'ohne.layer.ts'),
      `import { defineLayer } from '${ohne}';\n\n` +
        'export default defineLayer({\n' +
        "  codegen: [{ bucket: 'node', file: 'fixture.ts', code: () => 'export {};\\n' }],\n" +
        '});\n',
    );
    return app;
  }

  function seed(file: string, content: string): void {
    mkdirSync(join(file, '..'), { recursive: true });
    writeFileSync(file, content);
  }

  before(() => {
    root = realpathSync(mkdtempSync(join(tmpdir(), 'ohne-generate-project-')));
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  afterEach(() => {
    useLayers().clear();
  });

  it('writes every generator and layer codegen file, returning their absolute paths', async () => {
    const app = makeApp('app');
    await loadLayers(app);

    const written = await generateProject(app);

    const expected = [
      'browser/messages.ts',
      'browser/routes.ts',
      'browser/tsconfig.json',
      'node/database.ts',
      'node/fixture.ts',
      'node/flows.ts',
      'node/layer-name.ts',
      'node/messages.ts',
      'node/middleware.ts',
      'node/resolved-config.ts',
      'node/roles.ts',
      'node/routes.ts',
      'node/skills.ts',
      'shared/database.ts',
      'shared/flows.ts',
      'shared/messages.ts',
      'shared/roles.ts',
      'shared/routes.ts',
      'shared/skills.ts',
    ].map((file) => join(app, '.ohne', file));
    deepStrictEqual([...written].sort(), expected);
    for (const file of written) strictEqual(existsSync(file), true);
  });

  it('prunes the generated files the run did not write and leaves hand-written ones', async () => {
    const app = makeApp('stale');
    const current = join(app, '.ohne', 'node', 'dropped.ts');
    const foreign = join(app, '.ohne', 'old.ts');
    const own = join(app, '.ohne', 'node', 'notes.ts');
    seed(current, `${BANNER}\n`);
    seed(foreign, '// Generated by ohne 0.0.0. Do not edit.\n');
    seed(own, 'export const notes = true;\n');
    await loadLayers(app);

    const written = await generateProject(app);

    strictEqual(existsSync(current), false);
    strictEqual(existsSync(foreign), false);
    strictEqual(existsSync(own), true);
    for (const file of written) strictEqual(existsSync(file), true);
  });

  it('keeps every file on a rerun that changes nothing', async () => {
    const app = makeApp('rerun');
    await loadLayers(app);

    const first = await generateProject(app);
    const second = await generateProject(app);

    deepStrictEqual(second, first);
    for (const file of second) strictEqual(existsSync(file), true);
  });

  it('returns an empty list and writes nothing when no package.json is found', async () => {
    const nowhere = join(root, 'nowhere');

    deepStrictEqual(await generateProject(nowhere), []);
    strictEqual(existsSync(nowhere), false);
  });
});
