import { strictEqual } from 'node:assert';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, before, describe, it } from 'node:test';

import { generateLayerName, useLayers } from '../../../src/ohne/index.ts';

interface PackageSpec {
  name: string;
  ohne?: boolean;
  dependencies?: Record<string, string>;
}

describe('generateLayerName', () => {
  let root: string;

  function writePackage(at: string, spec: PackageSpec): void {
    mkdirSync(at, { recursive: true });
    const { ohne, ...manifest } = spec;
    writeFileSync(join(at, 'package.json'), JSON.stringify(manifest));
    if (ohne) writeFileSync(join(at, 'ohne.config.ts'), '');
  }

  function makeApp(name: string, app: Partial<PackageSpec>, deps: PackageSpec[]): string {
    const dir = join(root, name);
    writePackage(dir, { name, ohne: true, ...app });
    for (const dep of deps) writePackage(join(dir, 'node_modules', dep.name), dep);
    return dir;
  }

  before(() => {
    root = mkdtempSync(join(tmpdir(), 'ohne-gen-layer-'));
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('writes a union of the ohne layer names, excluding the app itself', async () => {
    const app = makeApp('app1', { dependencies: { a: '*', plain: '*' } }, [
      { name: 'a', ohne: true },
      { name: 'plain', dependencies: { c: '*' } },
      { name: 'c', ohne: true },
    ]);

    const path = await generateLayerName(app);
    strictEqual(path?.endsWith('/.ohne/node/layer-name.ts'), true);
    strictEqual(
      readFileSync(path!, 'utf8'),
      '// Generated by ohne. Do not edit.\n' +
        "import type {} from 'ohne';\n" +
        '\n' +
        "declare module 'ohne' {\n" +
        '  interface KnownLayers {\n' +
        "    'a': true;\n" +
        "    'c': true;\n" +
        '  }\n' +
        '}\n',
    );
  });

  it('emits an empty interface when the closure has no ohne layers', async () => {
    const app = makeApp('app2', { dependencies: { plain: '*' } }, [{ name: 'plain' }]);

    const path = await generateLayerName(app);
    strictEqual(
      readFileSync(path!, 'utf8'),
      '// Generated by ohne. Do not edit.\n' +
        "import type {} from 'ohne';\n" +
        '\n' +
        "declare module 'ohne' {\n" +
        '  interface KnownLayers {}\n' +
        '}\n',
    );
  });

  it('honors Config.dirs.codegen for the output directory', async () => {
    const app = makeApp('app3', { dependencies: { a: '*' } }, [{ name: 'a', ohne: true }]);

    const layers = useLayers();
    layers.add({ path: app, input: { dirs: { codegen: 'generated' } } });
    try {
      const path = await generateLayerName(app);
      strictEqual(path?.endsWith('/generated/node/layer-name.ts'), true);
      strictEqual(
        readFileSync(path!, 'utf8'),
        '// Generated by ohne. Do not edit.\n' +
          "import type {} from 'ohne';\n" +
          '\n' +
          "declare module 'ohne' {\n" +
          '  interface KnownLayers {\n' +
          "    'a': true;\n" +
          '  }\n' +
          '}\n',
      );
    } finally {
      layers.remove(app);
    }
  });

  it('returns null when no package.json is found', async () => {
    strictEqual(await generateLayerName(join(root, 'nowhere')), null);
  });
});
