import { rejects, strictEqual } from 'node:assert';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, afterEach, before, describe, it } from 'node:test';

import { generateMessages, loadLayers, useLayers } from '../../../src/ohne/index.ts';

interface PackageSpec {
  name: string;
  ohne?: boolean;
  dependencies?: Record<string, string>;
}

describe('generateMessages', () => {
  let root: string;

  function writePackage(at: string, spec: PackageSpec): void {
    mkdirSync(at, { recursive: true });
    const { ohne, ...manifest } = spec;
    writeFileSync(join(at, 'package.json'), JSON.stringify(manifest));
    if (ohne) writeFileSync(join(at, 'ohne.config.ts'), '');
  }

  function writeMessages(layerDir: string, relative: string, data: unknown): void {
    const file = join(layerDir, 'messages', relative);
    mkdirSync(join(file, '..'), { recursive: true });
    writeFileSync(file, JSON.stringify(data));
  }

  before(() => {
    root = realpathSync(mkdtempSync(join(tmpdir(), 'ohne-gen-messages-')));
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  afterEach(() => {
    for (const layer of useLayers().layers()) useLayers().remove(layer.path);
  });

  it('types each key and registers each language catalog', async () => {
    const app = join(root, 'app');
    writePackage(app, { name: 'app', ohne: true });
    writeMessages(app, 'en.json', {
      'field.required': 'This field is required',
      'field.minLength': 'Must be at least {min} {min, plural, one {character} other {characters}}',
    });
    writeMessages(app, 'de.json', {
      'field.required': 'Pflichtfeld',
      'field.minLength': 'Mindestens {min, plural, one {# Zeichen} other {# Zeichen}}',
    });

    await loadLayers(app);
    const path = await generateMessages(app);
    strictEqual(path?.endsWith('/.ohne/messages.ts'), true);
    const out = readFileSync(path!, 'utf8');

    strictEqual(out.includes("import { useMessages } from 'ohne';"), true);
    strictEqual(out.includes('interface KnownMessages {'), true);
    strictEqual(out.includes("'field.required': {};"), true);
    strictEqual(out.includes("'field.minLength': { min: number };"), true);

    strictEqual(out.includes('const messages = useMessages();'), true);
    strictEqual(out.includes("messages.register('en', {"), true);
    strictEqual(out.includes("messages.register('de', {"), true);
    strictEqual(out.includes("'field.required': 'This field is required',"), true);
  });

  it('types a select parameter as a union of its keywords', async () => {
    const app = join(root, 'select');
    writePackage(app, { name: 'select', ohne: true });
    writeMessages(app, 'en.json', {
      status: '{state, select, active {Active} paused {Paused} other {Unknown}}',
    });

    await loadLayers(app);
    const out = readFileSync((await generateMessages(app))!, 'utf8');
    strictEqual(out.includes("status: { state: 'active' | 'paused' };"), true);
  });

  it('throws when a key has different parameters across languages', async () => {
    const app = join(root, 'mismatch');
    writePackage(app, { name: 'mismatch', ohne: true });
    writeMessages(app, 'en.json', { greeting: 'Hi {name}' });
    writeMessages(app, 'de.json', { greeting: 'Hallo {count, number}' });

    await loadLayers(app);
    await rejects(
      generateMessages(app),
      /Message `greeting` has different parameters across languages/,
    );
  });

  it('throws on a malformed ICU template', async () => {
    const app = join(root, 'malformed');
    writePackage(app, { name: 'malformed', ohne: true });
    writeMessages(app, 'en.json', { broken: 'Hello {name' });

    await loadLayers(app);
    await rejects(generateMessages(app), /Invalid message `broken` for `en`/);
  });

  it('emits an empty interface when there are no messages', async () => {
    const app = join(root, 'empty');
    writePackage(app, { name: 'empty', ohne: true });

    await loadLayers(app);
    const path = await generateMessages(app);
    strictEqual(
      readFileSync(path!, 'utf8'),
      '// Generated by ohne. Do not edit.\n' +
        "import type {} from 'ohne';\n" +
        '\n' +
        "declare module 'ohne' {\n" +
        '  interface KnownMessages {}\n' +
        '}\n',
    );
  });

  it('returns null when no package.json is found', async () => {
    strictEqual(await generateMessages(join(root, 'nowhere')), null);
  });
});
