import { strictEqual } from 'node:assert';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, afterEach, before, describe, it } from 'node:test';

import { generateRoutes, loadLayers, useLayers } from '../../../src/ohne/index.ts';

interface PackageSpec {
  name: string;
  ohne?: boolean;
  dependencies?: Record<string, string>;
}

describe('generateRoutes', () => {
  let root: string;

  function writePackage(at: string, spec: PackageSpec): void {
    mkdirSync(at, { recursive: true });
    const { ohne, ...manifest } = spec;
    writeFileSync(join(at, 'package.json'), JSON.stringify(manifest));
    if (ohne) writeFileSync(join(at, 'ohne.config.ts'), '');
  }

  function writeRoute(layerDir: string, relative: string): void {
    const file = join(layerDir, 'api', relative);
    mkdirSync(join(file, '..'), { recursive: true });
    writeFileSync(file, 'export default () => null\n');
  }

  before(() => {
    root = realpathSync(mkdtempSync(join(tmpdir(), 'ohne-gen-routes-')));
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  afterEach(() => {
    for (const layer of useLayers().layers()) useLayers().remove(layer.path);
  });

  it('emits imports, types, and registrations for the combined table', async () => {
    const app = join(root, 'app');
    writePackage(app, { name: 'app', ohne: true, dependencies: { a: '*' } });
    writePackage(join(app, 'node_modules', 'a'), { name: 'a', ohne: true });

    writeRoute(join(app, 'node_modules', 'a'), 'index.get.ts');
    writeRoute(app, 'health.ts');
    writeRoute(app, 'users/[id].get.ts');

    await loadLayers(app);
    const path = await generateRoutes(app);
    strictEqual(path?.endsWith('/.ohne/routes.ts'), true);
    const out = readFileSync(path!, 'utf8');

    strictEqual(out.includes("import { useRoutes } from 'ohne';"), true);
    strictEqual(out.includes('interface KnownRoutes {'), true);
    strictEqual(out.includes("'/health': typeof h0;"), true);
    strictEqual(out.includes("'GET /': typeof h1;"), true);
    strictEqual(out.includes("'GET /users/[id]': typeof h2;"), true);

    strictEqual(out.includes('const routes = useRoutes();'), true);
    strictEqual(out.includes("routes.register('/health', {"), true);
    strictEqual(out.includes('method: null,'), true);
    strictEqual(out.includes("pattern: '/users/[id]',"), true);
    strictEqual(out.includes("layer: 'a',"), true);
    strictEqual(out.includes("layer: 'app',"), true);
    strictEqual(out.includes('handler: h2,'), true);

    strictEqual(out.includes("import h0 from '../api/health.ts';"), true);
    strictEqual(out.includes("import h1 from '../node_modules/a/api/index.get.ts';"), true);
  });

  it('emits an empty interface when there are no routes', async () => {
    const app = join(root, 'empty');
    writePackage(app, { name: 'empty', ohne: true });

    await loadLayers(app);
    const path = await generateRoutes(app);
    strictEqual(
      readFileSync(path!, 'utf8'),
      '// Generated by ohne. Do not edit.\n' +
        "import type {} from 'ohne';\n" +
        '\n' +
        "declare module 'ohne' {\n" +
        '  interface KnownRoutes {}\n' +
        '}\n',
    );
  });

  it('returns null when no package.json is found', async () => {
    strictEqual(await generateRoutes(join(root, 'nowhere')), null);
  });
});
