import { strictEqual } from 'node:assert';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, afterEach, before, describe, it } from 'node:test';

import { generateMiddleware, loadLayers, useLayers } from '../../../src/ohne/index.ts';

interface PackageSpec {
  name: string;
  ohne?: boolean;
  dependencies?: Record<string, string>;
}

describe('generateMiddleware', () => {
  let root: string;

  function writePackage(at: string, spec: PackageSpec): void {
    mkdirSync(at, { recursive: true });
    const { ohne, ...manifest } = spec;
    writeFileSync(join(at, 'package.json'), JSON.stringify(manifest));
    if (ohne) writeFileSync(join(at, 'ohne.config.ts'), '');
  }

  function writeMiddleware(layerDir: string, relative: string): void {
    const file = join(layerDir, 'middleware', relative);
    mkdirSync(join(file, '..'), { recursive: true });
    writeFileSync(file, 'export default () => undefined\n');
  }

  before(() => {
    root = realpathSync(mkdtempSync(join(tmpdir(), 'ohne-gen-middleware-')));
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  afterEach(() => {
    for (const layer of useLayers().layers()) useLayers().remove(layer.path);
  });

  it('emits imports and registrations, globals first', async () => {
    const app = join(root, 'app');
    writePackage(app, { name: 'app', ohne: true, dependencies: { a: '*' } });
    writePackage(join(app, 'node_modules', 'a'), { name: 'a', ohne: true });

    writeMiddleware(join(app, 'node_modules', 'a'), '10-auth.ts');
    writeMiddleware(app, '20-locale.ts');
    writeMiddleware(app, 'global/secure.ts');

    await loadLayers(app);
    const path = await generateMiddleware(app);
    strictEqual(path?.endsWith('/.ohne/middleware.ts'), true);
    const out = readFileSync(path!, 'utf8');

    strictEqual(out.includes("import { useMiddleware } from 'ohne';"), true);
    strictEqual(out.includes("import m0 from '../middleware/global/secure.ts';"), true);
    strictEqual(out.includes("import m1 from '../node_modules/a/middleware/10-auth.ts';"), true);
    strictEqual(out.includes("import m2 from '../middleware/20-locale.ts';"), true);

    strictEqual(out.includes('interface KnownMiddleware {'), true);
    strictEqual(out.includes("'global-secure': typeof m0;"), true);
    strictEqual(out.includes("'10-auth': typeof m1;"), true);
    strictEqual(out.includes("'20-locale': typeof m2;"), true);

    const namedBlock = out.slice(
      out.indexOf('interface KnownNamedMiddleware {'),
      out.indexOf('}', out.indexOf('interface KnownNamedMiddleware {')),
    );
    strictEqual(namedBlock.includes("'10-auth': typeof m1;"), true);
    strictEqual(namedBlock.includes("'20-locale': typeof m2;"), true);
    strictEqual(namedBlock.includes('global-secure'), false);

    strictEqual(out.includes('const middleware = useMiddleware();'), true);
    strictEqual(out.includes("middleware.registerGlobal('global-secure', m0);"), true);
    strictEqual(out.includes("middleware.register('10-auth', m1);"), true);
    strictEqual(out.includes("middleware.register('20-locale', m2);"), true);
  });

  it('emits empty interfaces when there is no middleware', async () => {
    const app = join(root, 'empty');
    writePackage(app, { name: 'empty', ohne: true });

    await loadLayers(app);
    const path = await generateMiddleware(app);
    strictEqual(
      readFileSync(path!, 'utf8'),
      '// Generated by ohne. Do not edit.\n' +
        "import type {} from 'ohne';\n" +
        '\n' +
        "declare module 'ohne' {\n" +
        '  interface KnownMiddleware {}\n' +
        '  interface KnownNamedMiddleware {}\n' +
        '}\n',
    );
  });

  it('returns null when no package.json is found', async () => {
    strictEqual(await generateMiddleware(join(root, 'nowhere')), null);
  });
});
