import { deepStrictEqual, ok, strictEqual } from 'node:assert';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, afterEach, before, describe, it } from 'node:test';

import { generateBrowserTSConfig, loadLayers, useLayers } from '../../../src/ohne/index.ts';

describe('generateBrowserTSConfig', () => {
  let root: string;

  before(() => {
    root = realpathSync(mkdtempSync(join(tmpdir(), 'ohne-gen-browser-tsconfig-')));
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  afterEach(() => {
    useLayers().clear();
  });

  it('writes an editor-discoverable config extending the framework browser tsconfig', async () => {
    const app = join(root, 'app');
    mkdirSync(app, { recursive: true });
    writeFileSync(join(app, 'package.json'), JSON.stringify({ name: 'app', type: 'module' }));
    writeFileSync(join(app, 'ohne.config.ts'), 'export default {};\n');

    await loadLayers(app);
    const path = await generateBrowserTSConfig(app);

    strictEqual(path, join(app, '.ohne', 'browser', 'tsconfig.json'));
    const lines = readFileSync(path ?? '', 'utf8').split('\n');
    strictEqual(lines[0], '// Generated by ohne. Do not edit.');
    const config = JSON.parse(lines.slice(1).join('\n')) as { extends: string; include: string[] };
    ok(existsSync(config.extends));
    ok(config.extends.endsWith('tsconfig.browser.json'));
    deepStrictEqual(config.include, ['./**/*.ts']);
  });
});
