import { strictEqual } from 'node:assert';
import { mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, afterEach, before, describe, it } from 'node:test';

import { generateRoles, loadLayers, useLayers } from '../../../src/ohne/index.ts';

describe('generateRoles', () => {
  let root: string;

  function writePackage(at: string, name: string, config = 'export default {};\n'): void {
    mkdirSync(at, { recursive: true });
    writeFileSync(join(at, 'package.json'), JSON.stringify({ name, type: 'module' }));
    writeFileSync(join(at, 'ohne.config.ts'), config);
  }

  function writeRole(dir: string, relative: string, capabilities: string[]): void {
    const file = join(dir, 'roles', relative);
    mkdirSync(join(file, '..'), { recursive: true });
    writeFileSync(file, `export default { capabilities: ${JSON.stringify(capabilities)} };\n`);
  }

  before(() => {
    root = realpathSync(mkdtempSync(join(tmpdir(), 'ohne-gen-roles-')));
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  afterEach(() => {
    useLayers().clear();
  });

  it('emits imports, the `KnownRoles` augmentation, and registrations', async () => {
    const app = join(root, 'app');
    writePackage(app, 'app');
    writeRole(app, 'admin.ts', ['*']);
    writeRole(app, 'shop/manager.ts', ['collection.Products.*']);

    await loadLayers(app);
    const path = await generateRoles(app);
    strictEqual(path?.endsWith('/.ohne/node/roles.ts'), true);
    const out = readFileSync(path!, 'utf8');

    strictEqual(out.includes("import { useRoles } from 'ohne';"), true);
    strictEqual(out.includes("import r0 from '../../roles/admin.ts';"), true);
    strictEqual(out.includes("import r1 from '../../roles/shop/manager.ts';"), true);
    strictEqual(out.includes('interface KnownRoles {'), true);
    strictEqual(out.includes('admin: true;'), true);
    strictEqual(out.includes("'shop-manager': true;"), true);
    strictEqual(out.includes('const roles = useRoles();'), true);
    strictEqual(out.includes("roles.register('admin', { name: 'admin', role: r0 });"), true);
    strictEqual(
      out.includes("roles.register('shop-manager', { name: 'shop-manager', role: r1 });"),
      true,
    );
  });

  it('drops names in `disable.roles`', async () => {
    const app = join(root, 'disabled');
    writePackage(app, 'disabled', "export default { disable: { roles: ['admin'] } };\n");
    writeRole(app, 'admin.ts', ['*']);
    writeRole(app, 'editor.ts', ['collection.Posts.read']);

    await loadLayers(app);
    const out = readFileSync((await generateRoles(app))!, 'utf8');

    strictEqual(out.includes('editor: true;'), true);
    strictEqual(out.includes('admin'), false);
  });

  it('emits an empty interface when there are no roles', async () => {
    const app = join(root, 'empty');
    writePackage(app, 'empty');

    await loadLayers(app);
    const path = await generateRoles(app);
    strictEqual(
      readFileSync(path!, 'utf8'),
      '// Generated by ohne. Do not edit.\n' +
        "import type {} from 'ohne';\n" +
        '\n' +
        "declare module 'ohne' {\n" +
        '  interface KnownRoles {}\n' +
        '}\n',
    );
  });

  it('returns null when no package.json is found', async () => {
    strictEqual(await generateRoles(join(root, 'nowhere')), null);
  });
});
