import { deepStrictEqual, strictEqual } from 'node:assert';
import { existsSync, mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { after, before, describe, it } from 'node:test';

import { pruneCodegen } from '../../../src/ohne/index.ts';

const BANNER = '// Generated by ohne. Do not edit.\n';

describe('pruneCodegen', () => {
  let root: string;

  function makeApp(name: string): string {
    const app = join(root, name);
    mkdirSync(join(app, '.ohne', 'node'), { recursive: true });
    writeFileSync(join(app, 'package.json'), JSON.stringify({ name, type: 'module' }));
    return app;
  }

  before(() => {
    root = realpathSync(mkdtempSync(join(tmpdir(), 'ohne-prune-codegen-')));
  });

  after(() => {
    rmSync(root, { recursive: true, force: true });
  });

  it('removes every generated file the current run did not write, at any depth', async () => {
    const app = makeApp('stale');
    const kept = join(app, '.ohne', 'node', 'routes.ts');
    const flat = join(app, '.ohne', 'flat.ts');
    const nested = join(app, '.ohne', 'node', 'stale.ts');
    for (const file of [kept, flat, nested]) writeFileSync(file, BANNER);

    const removed = await pruneCodegen(app, [kept]);

    deepStrictEqual(removed.sort(), [flat, nested]);
    strictEqual(existsSync(kept), true);
    strictEqual(existsSync(flat), false);
    strictEqual(existsSync(nested), false);
  });

  it('never touches a file without the generated banner', async () => {
    const app = makeApp('handwritten');
    const own = join(app, '.ohne', 'node', 'notes.ts');
    writeFileSync(own, 'export const mine = true;\n');

    deepStrictEqual(await pruneCodegen(app, []), []);
    strictEqual(existsSync(own), true);
  });

  it('leaves hidden entries in place', async () => {
    const app = makeApp('hidden');
    const ignore = join(app, '.ohne', '.gitignore');
    writeFileSync(ignore, '*\n');

    deepStrictEqual(await pruneCodegen(app, []), []);
    strictEqual(existsSync(ignore), true);
  });

  it('returns empty when the codegen dir does not exist', async () => {
    const app = join(root, 'bare');
    mkdirSync(app, { recursive: true });
    writeFileSync(join(app, 'package.json'), JSON.stringify({ name: 'bare', type: 'module' }));

    deepStrictEqual(await pruneCodegen(app, []), []);
  });
});
