import { pathToFileURL } from 'node:url';

import { exists, readFile } from '../../utils/fs/index.ts';
import { first, isNull, isUndefined, joinPath, relativePath } from '../../utils/index.ts';
import { bannerVersion, codegenDir } from '../codegen/codegen-dir.ts';
import { generateProject } from '../codegen/generate-project.ts';
import { useEnv } from '../env/use-env.ts';
import { version } from '../meta/version.ts';
import { usePrinter } from '../printer/use-printer.ts';
import { bootLayers } from './boot-layers.ts';

/**
 * Boots the loaded project the way its API server does, up to the database.
 *
 * Runs every layer's boot files, then regenerates the types.
 * Codegen is skipped when the `SKIP_CODEGEN` env is truthy.
 * A skipped codegen still warns when another ohne version generated the files.
 * Last, it imports the generated registrations.
 *
 * Reads the stack from `useLayers`, so `loadLayers` must have run first.
 * The app root is the nearest `package.json` above `from` (default `process.cwd()`).
 *
 * @example
 * ```ts
 * await loadProjectEnv('/srv/app')
 * await loadLayers('/srv/app')
 * await bootProject('/srv/app')
 * ```
 */
export async function bootProject(from: string = process.cwd()): Promise<void> {
  await bootLayers();

  const skipCodegen = useEnv().get('SKIP_CODEGEN');
  if (!skipCodegen) await generateProject(from);

  // The component tables live in the node bucket: importing runs the registrations.
  const dir = await codegenDir(from);
  if (isNull(dir)) return;
  const files: string[] = [];
  for (const name of [
    'node/routes.ts',
    'node/middleware.ts',
    'node/messages.ts',
    'node/database.ts',
    'node/roles.ts',
    'node/skills.ts',
    'node/flows.ts',
  ]) {
    const file = joinPath(dir, name);
    if (await exists(file)) files.push(file);
  }
  const head = first(files);
  if (skipCodegen && !isUndefined(head)) await warnStaleCodegen(head, dir);
  for (const file of files) await import(pathToFileURL(file).href);
}

/**
 * Warns when the generated files a `SKIP_CODEGEN` boot trusts were stamped by another ohne version.
 * `file` is the first generated registration file; its banner records the version that wrote it.
 */
async function warnStaleCodegen(file: string, dir: string): Promise<void> {
  const content = await readFile(file);
  if (isNull(content)) return;
  const stamped = bannerVersion(content);
  if (stamped === version) return;
  usePrinter().warnBlock({
    title: 'Generated files are stale',
    body: [
      isNull(stamped)
        ? `They carry no version stamp, so an earlier ohne than \`${version}\` generated them.`
        : `They were generated by ohne \`${stamped}\`; you are running \`${version}\`.`,
      '',
      'Run `ohne prepare` to regenerate them.',
    ],
    path: relativePath(process.cwd(), dir),
  });
}
