import { findUp } from '../../utils/fs/index.ts';
import { dirname, isNull, joinPath } from '../../utils/index.ts';
import { DIR_DEFAULTS } from '../layers/config.ts';
import { useLayers } from '../layers/use-layers.ts';

/**
 * A codegen output bucket, partitioning generated files by which TypeScript program consumes them.
 * `shared` holds pure types both programs include.
 * `node` holds `ohne` augmentations and registrations; `browser` holds `ohne/dashboard` augmentations.
 * The two `tsconfig`s route each bucket by directory.
 */
export type CodegenBucket = 'shared' | 'node' | 'browser';

/**
 * First line of every file ohne generates.
 * `pruneCodegen` deletes only files that start with it, so a hand-written file is never removed.
 */
export const BANNER = '// Generated by ohne. Do not edit.';

/**
 * Resolves the app's codegen output directory as an absolute path.
 *
 * Reads the app's own `dirs.codegen`, found by its directory in the layer registry.
 * The output directory is the app's choice, never inherited from a dependency through the merge.
 * Falls back to `DIR_DEFAULTS.codegen` when the app does not set it.
 *
 * The app root is the nearest `package.json` above `from`.
 * Returns `null` when no `package.json` is found.
 */
export async function codegenDir(from: string): Promise<string | null> {
  const manifestPath = await findUp('package.json', from);
  if (isNull(manifestPath)) return null;

  const appDir = dirname(manifestPath);
  const own = useLayers()
    .layers()
    .find((layer) => layer.path === appDir)?.input.dirs?.codegen;
  return joinPath(appDir, own ?? DIR_DEFAULTS.codegen);
}

/**
 * Resolves a codegen output bucket as an absolute path, or `null` when there is no codegen dir.
 * A generator writes into its bucket so the `node` and `browser` type programs never load each other's.
 */
export async function codegenBucket(from: string, bucket: CodegenBucket): Promise<string | null> {
  const dir = await codegenDir(from);
  return isNull(dir) ? null : joinPath(dir, bucket);
}
