import {
  type CodeBuilder,
  createCodeBuilder,
  createCodeGenerator,
  propertyKey,
} from '../../utils/codegen/index.ts';
import { isEmpty, isNull, isPlainObject, merge } from '../../utils/index.ts';
import { useLayers } from '../layers/use-layers.ts';
import { codegenDir } from './codegen-dir.ts';

const BANNER = '// Generated by ohne. Do not edit.';

function writeDefaults(code: CodeBuilder, defaults: Record<string, unknown>): void {
  for (const [name, value] of Object.entries(defaults)) {
    if (isPlainObject(value)) {
      code.line(`${propertyKey(name)}: {`);
      code.indent(() => writeDefaults(code, value));
      code.line('};');
    } else {
      code.line(`${propertyKey(name)}: true;`);
    }
  }
}

/**
 * Generates the `ResolvedConfig` type from the layers' merged defaults.
 * Emits `resolved-config.ts` so `ResolvedConfig` makes every defaulted field required, keeping its type.
 * A field set only by a runtime `input` stays optional; only a default makes it required.
 *
 * The app root is the nearest `package.json` above `from` (default `process.cwd()`).
 * Output lands in the app's own `dirs.codegen` (default `.ohne`), resolved against that root.
 *
 * The file is rewritten only when its contents change.
 * Returns the absolute path written, or `null` when no `package.json` is found.
 */
export async function generateResolvedConfig(from: string = process.cwd()): Promise<string | null> {
  const dir = await codegenDir(from);
  if (isNull(dir)) return null;

  const defaults = useLayers()
    .layers()
    .reduce<Record<string, unknown>>((acc, layer) => merge(acc, layer.defaults), {});

  const code = createCodeBuilder();
  code.line("import type {} from 'ohne';");
  code.line();
  code.line("declare module 'ohne' {");
  code.indent(() => {
    if (isEmpty(defaults)) {
      code.line('interface ConfigExtensions {}');
    } else {
      code.line('interface ConfigExtensions {');
      code.indent(() => {
        code.line('defaults: {');
        code.indent(() => writeDefaults(code, defaults));
        code.line('};');
      });
      code.line('}');
    }
  });
  code.line('}');

  const gen = createCodeGenerator({ dir, banner: BANNER });
  await gen.write('resolved-config.ts', code.toString());
  return gen.path('resolved-config.ts');
}
