import { createCode, createGenerator, union } from '../../utils/codegen/index.ts';
import { findUp } from '../../utils/fs/index.ts';
import { dirname, isNull, joinPath } from '../../utils/index.ts';
import { useConfig } from '../layers/use-config.ts';
import { resolveOhneApps } from '../project/resolve-ohne-apps.ts';

const BANNER = '// Generated by ohne. Do not edit.';

/**
 * Generates the `LayerName` type from the app's ohne dependency closure.
 * Emits `layer-name.ts` declaring a string-literal union of every layer's name, or `never` when none.
 *
 * The app root is the nearest `package.json` above `from` (default `process.cwd()`).
 * Output lands in `Config.dirs.codegen` (default `.ohne`), resolved against that root.
 *
 * The file is rewritten only when its contents change.
 * Returns the absolute path written, or `null` when no `package.json` is found.
 */
export async function generateLayerName(from: string = process.cwd()): Promise<string | null> {
  const manifestPath = await findUp('package.json', from);
  if (isNull(manifestPath)) return null;

  const names = await resolveOhneApps(from);
  const dir = joinPath(dirname(manifestPath), useConfig().dirs?.codegen ?? '.ohne');

  const code = createCode();
  code.line(`export type LayerName = ${union(names)};`);

  const gen = createGenerator({ dir, banner: BANNER });
  await gen.write('layer-name.ts', code.toString());
  return gen.path('layer-name.ts');
}
