import {
  createCodeBuilder,
  createCodeGenerator,
  literalString,
} from '../../utils/codegen/index.ts';
import { findUp } from '../../utils/fs/index.ts';
import { dirname, isNull, joinPath } from '../../utils/index.ts';
import { useConfig } from '../layers/use-config.ts';
import { resolveOhneApps } from '../project/resolve-ohne-apps.ts';

const BANNER = '// Generated by ohne. Do not edit.';

/**
 * Generates the `LayerName` type from the app's ohne dependency closure.
 * Emits `layer-name.ts` so `LayerName` resolves to a string-literal union of every layer's name.
 * Falls back to `string` when the closure has no ohne layers.
 *
 * The app root is the nearest `package.json` above `from` (default `process.cwd()`).
 * Output lands in `Config.dirs.codegen` (default `.ohne`), resolved against that root.
 *
 * The file is rewritten only when its contents change.
 * Returns the absolute path written, or `null` when no `package.json` is found.
 */
export async function generateLayerName(from: string = process.cwd()): Promise<string | null> {
  const manifestPath = await findUp('package.json', from);
  if (isNull(manifestPath)) return null;

  const names = await resolveOhneApps(from);
  const dir = joinPath(dirname(manifestPath), useConfig().dirs?.codegen ?? '.ohne');

  const code = createCodeBuilder();
  code.line("declare module 'ohne' {");
  code.indent(() => {
    if (names.length === 0) {
      code.line('interface KnownLayers {}');
    } else {
      code.line('interface KnownLayers {');
      code.indent(() => {
        for (const name of names) code.line(`${literalString(name)}: true;`);
      });
      code.line('}');
    }
  });
  code.line('}');
  code.line('export {};');

  const gen = createCodeGenerator({ dir, banner: BANNER });
  await gen.write('layer-name.ts', code.toString());
  return gen.path('layer-name.ts');
}
