import type { MessageMeta } from '../messages/messages.ts';

import {
  createCodeBuilder,
  createCodeGenerator,
  literalString,
  literalUnion,
  propertyKey,
} from '../../utils/codegen/index.ts';
import {
  errorMessage,
  groupBy,
  isNull,
  messageParamTypes,
  type MessageParamType,
  relativePath,
} from '../../utils/index.ts';
import { ohneError } from '../error/ohne-error.ts';
import { collectMessages } from '../messages/collect-messages.ts';
import { resolveOhneLayers } from '../project/resolve-ohne-layers.ts';
import { codegenDir } from './codegen-dir.ts';

const BANNER = '// Generated by ohne. Do not edit.';

/**
 * Generates the message catalog from every layer's messages directory.
 * Emits `messages.ts` so importing it registers each language's catalog into `useMessages`.
 * It types `KnownMessages` with every key mapped to the parameters its ICU template expects.
 *
 * Messages are read from each layer's `Config.dirs.messages` directory and merged per key.
 * A key's parameters must match across every language that defines it, or generation throws.
 *
 * The app root is the nearest `package.json` above `from` (default `process.cwd()`).
 * Output lands in the app's own `dirs.codegen` (default `.ohne`), resolved against that root.
 *
 * The file is rewritten only when its contents change.
 * Returns the absolute path written, or `null` when no `package.json` is found.
 */
export async function generateMessages(from: string = process.cwd()): Promise<string | null> {
  const dir = await codegenDir(from);
  if (isNull(dir)) return null;

  const messages = await collectMessages(await resolveOhneLayers(from));
  const keyTypes = unifyKeyTypes(messages);

  const code = createCodeBuilder();
  code.line(
    messages.length === 0 ? "import type {} from 'ohne';" : "import { useMessages } from 'ohne';",
  );
  code.line();

  code.line("declare module 'ohne' {");
  code.indent(() => {
    if (keyTypes.size === 0) {
      code.line('interface KnownMessages {}');
      return;
    }
    code.line('interface KnownMessages {');
    code.indent(() => {
      for (const [key, type] of keyTypes) code.line(`${propertyKey(key)}: ${type};`);
    });
    code.line('}');
  });
  code.line('}');

  if (messages.length > 0) {
    code.line();
    code.line('const messages = useMessages();');
    for (const [language, entries = []] of Object.entries(groupBy(messages, (m) => m.language))) {
      code.line(`messages.register(${literalString(language)}, {`);
      code.indent(() => {
        for (const entry of entries) {
          code.line(`${propertyKey(entry.key)}: ${literalString(entry.template)},`);
        }
      });
      code.line('});');
    }
  }

  const gen = createCodeGenerator({ dir, banner: BANNER });
  await gen.write('messages.ts', code.toString());
  return gen.path('messages.ts');
}

/**
 * Maps each key to its rendered parameter type, sorted by key for deterministic output.
 * Throws when a key's parameters disagree between two languages.
 */
function unifyKeyTypes(messages: readonly MessageMeta[]): Map<string, string> {
  const seen = new Map<string, { language: string; file: string; type: string }>();
  for (const message of messages) {
    const type = renderParamObject(paramsOf(message));
    const first = seen.get(message.key);
    if (!first) {
      seen.set(message.key, { language: message.language, file: message.file, type });
      continue;
    }
    if (first.type !== type) {
      throw ohneError({
        title: `Message \`${message.key}\` has different parameters across languages`,
        body: [
          `Every language must declare the same parameters for \`${message.key}\`.`,
          `\`${first.language}\` expects \`${first.type}\`; \`${message.language}\` expects \`${type}\`.`,
          '',
          `- \`${relativePath(process.cwd(), first.file)}\``,
          `- \`${relativePath(process.cwd(), message.file)}\``,
        ],
      });
    }
  }

  return new Map([...seen.keys()].sort().map((key) => [key, seen.get(key)!.type]));
}

function paramsOf(message: MessageMeta): Record<string, MessageParamType> {
  try {
    return messageParamTypes(message.template);
  } catch (error) {
    throw ohneError({
      title: `Invalid message \`${message.key}\` for \`${message.language}\``,
      body: errorMessage(error),
      path: message.file,
    });
  }
}

function renderParamObject(params: Record<string, MessageParamType>): string {
  const names = Object.keys(params).sort();
  if (names.length === 0) return '{}';
  const fields = names.map((name) => `${propertyKey(name)}: ${renderParamType(params[name]!)}`);
  return `{ ${fields.join('; ')} }`;
}

function renderParamType(type: MessageParamType): string {
  switch (type.kind) {
    case 'value':
      return 'string | number';
    case 'number':
      return 'number';
    case 'date':
      return 'Date | number';
    case 'choice':
      return type.options.length === 0 ? 'string' : literalUnion([...type.options].sort());
  }
}
