import {
  createCodeBuilder,
  createCodeGenerator,
  importSpecifier,
  literalString,
  propertyKey,
} from '../../utils/codegen/index.ts';
import { isNull } from '../../utils/index.ts';
import { useConfig } from '../layers/use-config.ts';
import { resolveOhneLayers } from '../project/resolve-ohne-layers.ts';
import { collectRoutes } from '../routes/collect-routes.ts';
import { routeID } from '../routes/route.ts';
import { codegenDir } from './codegen-dir.ts';

const BANNER = '// Generated by ohne. Do not edit.';

/**
 * Generates the route table from every layer's API directory.
 * Emits `routes.ts` so importing it registers each route into `useRoutes` and types `KnownRoutes`.
 * Each handler is statically imported from its source file by relative path.
 *
 * Routes are read from each layer's `Config.dirs.api` directory and combined.
 * A closer layer overrides an earlier route with the same id.
 * Routes matched by `Config.disable.routes` are then dropped.
 *
 * The app root is the nearest `package.json` above `from` (default `process.cwd()`).
 * Output lands in the app's own `dirs.codegen` (default `.ohne`), resolved against that root.
 *
 * The file is rewritten only when its contents change.
 * Returns the absolute path written, or `null` when no `package.json` is found.
 */
export async function generateRoutes(from: string = process.cwd()): Promise<string | null> {
  const dir = await codegenDir(from);
  if (isNull(dir)) return null;

  const routes = await collectRoutes(await resolveOhneLayers(from), {
    disable: useConfig().disable.routes,
  });

  const code = createCodeBuilder();
  code.line(
    routes.length === 0 ? "import type {} from 'ohne';" : "import { useRoutes } from 'ohne';",
  );
  routes.forEach((route, i) => {
    code.line(`import h${i} from ${literalString(importSpecifier(dir, route.file))};`);
  });
  code.line();

  code.line("declare module 'ohne' {");
  code.indent(() => {
    if (routes.length === 0) {
      code.line('interface KnownRoutes {}');
    } else {
      code.line('interface KnownRoutes {');
      code.indent(() => {
        routes.forEach((route, i) => {
          code.line(`${propertyKey(routeID(route.method, route.pattern))}: typeof h${i};`);
        });
      });
      code.line('}');
    }
  });
  code.line('}');

  if (routes.length > 0) {
    code.line();
    code.line('const routes = useRoutes();');
    routes.forEach((route, i) => {
      code.line(`routes.register(${literalString(routeID(route.method, route.pattern))}, {`);
      code.indent(() => {
        code.line(`method: ${isNull(route.method) ? 'null' : literalString(route.method)},`);
        code.line(`pattern: ${literalString(route.pattern)},`);
        code.line(`file: ${literalString(route.file)},`);
        code.line(`layer: ${literalString(route.layer)},`);
        code.line(`handler: h${i},`);
      });
      code.line('});');
    });
  }

  const gen = createCodeGenerator({ dir, banner: BANNER });
  await gen.write('routes.ts', code.toString());
  return gen.path('routes.ts');
}
