import {
  createCodeBuilder,
  createCodeGenerator,
  literalString,
  propertyKey,
} from '../../utils/codegen/index.ts';
import { findUp } from '../../utils/fs/index.ts';
import { dirname, isNull, joinPath, relativePath } from '../../utils/index.ts';
import { useConfig } from '../layers/use-config.ts';
import { resolveOhneLayers } from '../project/resolve-ohne-layers.ts';
import { collectRoutes } from '../routes/collect-routes.ts';
import { routeId } from '../routes/route.ts';

const BANNER = '// Generated by ohne. Do not edit.';

function importSpec(fromDir: string, file: string): string {
  const rel = relativePath(fromDir, file);
  return rel.startsWith('.') ? rel : `./${rel}`;
}

/**
 * Generates the route table from every layer's API directory.
 * Emits `routes.ts` so importing it registers each route into `useRoutes` and types `KnownRoutes`.
 * Each handler is statically imported from its source file by relative path.
 *
 * Routes are read from each layer's `Config.dirs.api` directory and combined.
 * A closer layer overrides an earlier route with the same id.
 * Routes matched by `Config.disable.routes` are then dropped.
 *
 * The app root is the nearest `package.json` above `from` (default `process.cwd()`).
 * Output lands in `Config.dirs.codegen` (default `.ohne`), resolved against that root.
 *
 * The file is rewritten only when its contents change.
 * Returns the absolute path written, or `null` when no `package.json` is found.
 */
export async function generateRoutes(from: string = process.cwd()): Promise<string | null> {
  const manifestPath = await findUp('package.json', from);
  if (isNull(manifestPath)) return null;

  const config = useConfig();
  const dir = joinPath(dirname(manifestPath), config.dirs?.codegen ?? '.ohne');
  const routes = await collectRoutes(await resolveOhneLayers(from), {
    disable: config.disable?.routes ?? [],
  });

  const code = createCodeBuilder();
  code.line(
    routes.length === 0 ? "import type {} from 'ohne';" : "import { useRoutes } from 'ohne';",
  );
  routes.forEach((route, i) => {
    code.line(`import h${i} from ${literalString(importSpec(dir, route.file))};`);
  });
  code.line();

  code.line("declare module 'ohne' {");
  code.indent(() => {
    if (routes.length === 0) {
      code.line('interface KnownRoutes {}');
    } else {
      code.line('interface KnownRoutes {');
      code.indent(() => {
        routes.forEach((route, i) => {
          code.line(`${propertyKey(routeId(route.method, route.pattern))}: typeof h${i};`);
        });
      });
      code.line('}');
    }
  });
  code.line('}');

  if (routes.length > 0) {
    code.line();
    code.line('const routes = useRoutes();');
    routes.forEach((route, i) => {
      code.line(`routes.register(${literalString(routeId(route.method, route.pattern))}, {`);
      code.indent(() => {
        code.line(`method: ${isNull(route.method) ? 'null' : literalString(route.method)},`);
        code.line(`pattern: ${literalString(route.pattern)},`);
        code.line(`file: ${literalString(route.file)},`);
        code.line(`layer: ${literalString(route.layer)},`);
        code.line(`handler: h${i},`);
      });
      code.line('});');
    });
  }

  const gen = createCodeGenerator({ dir, banner: BANNER });
  await gen.write('routes.ts', code.toString());
  return gen.path('routes.ts');
}
