import {
  createCodeBuilder,
  createCodeGenerator,
  importSpecifier,
  literalString,
  propertyKey,
} from '../../utils/codegen/index.ts';
import { isNull } from '../../utils/index.ts';
import { collectMiddleware } from '../middleware/collect-middleware.ts';
import { resolveOhneLayers } from '../project/resolve-ohne-layers.ts';
import { codegenDir } from './codegen-dir.ts';

const BANNER = '// Generated by ohne. Do not edit.';

/**
 * Generates the middleware table from every layer's middleware directory.
 * Emits `middleware.ts` so importing it registers each middleware into `useMiddleware`, in run order.
 * It also types `KnownMiddleware` with one member per name, so `MiddlewareKey` is the union of names.
 * Each middleware is statically imported from its source file by relative path.
 *
 * Middleware is read from each layer's `Config.dirs.middleware` directory and combined.
 * A closer layer overrides an earlier middleware with the same resolved name.
 *
 * The app root is the nearest `package.json` above `from` (default `process.cwd()`).
 * Output lands in the app's own `dirs.codegen` (default `.ohne`), resolved against that root.
 *
 * The file is rewritten only when its contents change.
 * Returns the absolute path written, or `null` when no `package.json` is found.
 */
export async function generateMiddleware(from: string = process.cwd()): Promise<string | null> {
  const dir = await codegenDir(from);
  if (isNull(dir)) return null;

  const middleware = await collectMiddleware(await resolveOhneLayers(from));

  const code = createCodeBuilder();
  code.line(
    middleware.length === 0
      ? "import type {} from 'ohne';"
      : "import { useMiddleware } from 'ohne';",
  );
  middleware.forEach((entry, i) => {
    code.line(`import m${i} from ${literalString(importSpecifier(dir, entry.file))};`);
  });
  code.line();

  code.line("declare module 'ohne' {");
  code.indent(() => {
    if (middleware.length === 0) {
      code.line('interface KnownMiddleware {}');
    } else {
      code.line('interface KnownMiddleware {');
      code.indent(() => {
        middleware.forEach((entry, i) => {
          code.line(`${propertyKey(entry.name)}: typeof m${i};`);
        });
      });
      code.line('}');
    }
  });
  code.line('}');

  if (middleware.length > 0) {
    code.line();
    code.line('const middleware = useMiddleware();');
    middleware.forEach((entry, i) => {
      code.line(`middleware.register(${literalString(entry.name)}, m${i});`);
    });
  }

  const gen = createCodeGenerator({ dir, banner: BANNER });
  await gen.write('middleware.ts', code.toString());
  return gen.path('middleware.ts');
}
